/* this schema was written as a backend for an OpenOffice Base interface, and so uses the HSQLDB flabour of SQL syntax */
/* fully capitalized field names are used b/c OpenOffice converts everything to caps automatically for some reason */
/* http://hsqldb.org/ */



DROP TABLE IF EXISTS CODEDLOCATION;
DROP TABLE IF EXISTS CODEDTENDERNOTICE;
DROP TABLE IF EXISTS TENDERNOTICE;
DROP TABLE IF EXISTS CODEDSUPPLIER;
DROP TABLE IF EXISTS AWARD;
DROP TABLE IF EXISTS CODER;



CREATE TABLE TENDERNOTICE (
	ID int IDENTITY,
	TENDERNOTICENUMBER varchar(2000),
	STATUS varchar(2000),
	URL varchar(2000),
	CONTRACTDETAILS varchar(2000),
	ISSUER varchar(2000),
	PUBLICATIONDATE varchar(2000),
	PUBLISHEDIN varchar(2000),
	DOCUMENTPURCHASEDEADLINE varchar(2000),
	SUBMISSIONDEADLINE varchar(2000),
	OPENINGDATE varchar(2000),
	CONTRACTNAME varchar(2000),
	CONTRACTDESCRIPTION varchar(2000),
	COSTESTIMATE numeric,
	ESTIMATECURRENCY varchar(2000),
	DATASOURCE varchar(2000)
)

CREATE TABLE AWARD (
	ID int IDENTITY,
	COST_ESTIMATE numeric,
	ESTIMATE_CURRENCY varchar(2000),
	DATA_SOURCE varchar(2000),
	SCRAPED_SUPPLIER_NAME varchar(2000),
	SCRAPED_SUPPLIER_LOCATION varchar(2000)
)

CREATE TABLE CODER (
	ID int IDENTITY,
	NAME varchar(2000)
)

CREATE TABLE CODEDTENDERNOTICE (
	ID int IDENTITY,
	TENDER_NOTICE_ID int,
	CODER_ID int,
	TENDERNOTICENUMBER varchar(2000),
	CONTRACTNUMBER varchar(2000),
	CONTRACTTYPE varchar(2000),
	PROJECTNAME varchar(2000),
	PROJECTNUMBER varchar(2000),
	PROJECTFUNDER varchar(2000),
	CONTRACTNAME varchar(2000),
	CONTRACTDESCRIPTION varchar(2000),
	COSTESTIMATE numeric,
	ESTIMATECURRENCY varchar(2000),
	DATASOURCE varchar(2000),
	FOREIGN KEY (TENDER_NOTICE_ID) REFERENCES TENDERNOTICE (ID),
	FOREIGN KEY (CODER_ID) REFERENCES CODER(ID)

)

CREATE TABLE CODEDLOCATION (
	ID int IDENTITY,
	CODED_TENDER_NOTICE_ID int,
	ADM1 varchar(2000),
	ADM2 varchar(2000),
	ADM3 varchar(2000),
	ADM4 varchar(2000),
	WARD varchar(2000),
	OTHER_LOCATION varchar(2000),
	OTHER_LOCATION_DESC varchar(2000),
	ACTIVITY_DESC varchar(2000),
	FOREIGN KEY (CODED_TENDER_NOTICE_ID) REFERENCES CODEDTENDERNOTICE (ID)
)


CREATE TABLE CODEDSUPPLIER (
	ID int IDENTITY,
	AWARD_ID int,
	CODER_ID int,
	SUPPLIER_NAME varchar(2000),
	SUPPLIER_REGISTRATION_CODE varchar (2000),
	SUPPLIER_REGISTRATION_CODE_SOURCE varchar(2000),
	SUPPLIER_COUNTRY varchar(2000),
	ADM1 varchar(2000),
	ADM2 varchar(2000),
	ADM3 varchar(2000),
	ADM4 varchar(2000),
	WARD varchar(2000),
	OTHER_LOCATION varchar(2000),
	OTHER_LOCATION_DESC varchar(2000),
	FOREIGN KEY (AWARD_ID) REFERENCES AWARD (ID),
	FOREIGN KEY (CODER_ID) REFERENCES CODER(ID)
)


